version: "3"

services:
  mariadb:
    build: requirements/mariadb
    image: mariadb:local
    container_name: mariadb
    env_file:
      - .env
    networks:
      - def
    volumes:
      - db_volume:/var/lib/mysql
    restart: always
  wordpress:
    depends_on:
      - mariadb
    build: requirements/wordpress
    image: wordpress:local
    container_name: wordpress
    env_file:
      - .env
    networks:
      - def
    volumes:
      - wp_volume:/blog
    restart: always
  nginx:
    depends_on:
      - wordpress
    build: requirements/nginx
    image: nginx:local
    container_name: nginx
    ports:
      - "443:443"
    networks:
      - def
    volumes:
      - wp_volume:/blog
    env_file:
      - .env
    restart: always
volumes:
  db_volume:
    driver: local
    driver_opts:
      type: none
      o:    bind
      device: /home/ted-dafi/data/db
  wp_volume:
    driver: local
    driver_opts:
      type: none
      o:    bind
      device: /home/ted-dafi/data/wp

networks:
  def:
    driver: bridge